/**
 * Semantic color tokens for light / dark.
 * Brand core: navy #1E2A3A · electric cyan #00E5FF
 * Components must use these (Tailwind color names or var(--token)), never raw hex.
 */
export const themes = {
  light: {
    id: 'light',
    label: 'Light',
    mode: 'light',
    vars: {
      '--ink': '#1E2A3A',
      '--ink-soft': '#2F3F54',
      '--mist': '#E6EDF4',
      '--foam': '#F3F7FB',
      '--lagoon': '#00C4D9',
      '--lagoon-deep': '#0099AD',
      '--coral': '#E85D4C',
      '--sun': '#E8B84A',
      '--craton': '#1E2A3A',
      '--copper': '#00E5FF',
      '--hero-base': '#1E2A3A',
      '--hero-fg': '#F3F7FB',
      '--hero-muted': '#A8B7C7',
      '--hero-soft': '#D5E2EE',
      '--hero-body': '#B4C3D2',
      '--hero-cta': '#F3F7FB',
      '--hero-nav': '#C5D1DC',
      '--hero-veil': 'rgba(30, 42, 58, 0.45)',
      '--hero-veil-mid': 'rgba(30, 42, 58, 0.1)',
      '--hero-veil-edge': 'rgba(30, 42, 58, 0.3)',
      '--line': 'rgba(30, 42, 58, 0.12)',
      '--line-on-dark': 'rgba(243, 247, 251, 0.14)',
      '--highlight': 'rgba(0, 229, 255, 0.22)',
      '--signal-line': '#3A4A5C',
      '--signal-pulse': '#00E5FF',
      '--cursor': '#00E5FF',
    },
  },
  dark: {
    id: 'dark',
    label: 'Dark',
    mode: 'dark',
    vars: {
      '--foam': '#121A24',
      '--mist': '#1E2A3A',
      '--craton': '#0D141D',
      '--ink': '#E8EEF4',
      '--ink-soft': '#9AABBC',
      '--lagoon': '#00E5FF',
      '--lagoon-deep': '#33EBFF',
      '--copper': '#00E5FF',
      '--sun': '#E8B84A',
      '--coral': '#D96B5C',
      '--hero-base': '#1E2A3A',
      '--hero-fg': '#F3F7FB',
      '--hero-muted': '#8FA0B3',
      '--hero-soft': '#C9D6E3',
      '--hero-body': '#9AABBC',
      '--hero-cta': '#E8EEF4',
      '--hero-nav': '#A8B7C7',
      '--hero-veil': 'rgba(13, 20, 29, 0.5)',
      '--hero-veil-mid': 'rgba(13, 20, 29, 0.12)',
      '--hero-veil-edge': 'rgba(13, 20, 29, 0.35)',
      '--line': 'rgba(232, 238, 244, 0.1)',
      '--line-on-dark': 'rgba(243, 247, 251, 0.14)',
      '--highlight': 'rgba(0, 229, 255, 0.16)',
      '--signal-line': '#3A4A5C',
      '--signal-pulse': '#00E5FF',
      '--cursor': '#00E5FF',
    },
  },
}

export const defaultThemeId = 'light'

/** CSS custom property names exposed as Tailwind colors via @theme */
export const themeColorKeys = [
  'ink',
  'ink-soft',
  'mist',
  'foam',
  'lagoon',
  'lagoon-deep',
  'coral',
  'sun',
  'craton',
  'copper',
  'hero-base',
  'hero-fg',
  'hero-muted',
  'hero-soft',
  'hero-body',
  'hero-cta',
  'hero-nav',
  'line',
  'line-on-dark',
  'highlight',
  'signal-line',
  'signal-pulse',
  'cursor',
]
